[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dummypy"
version = "0.1.0"
description = "A dummy Python analytics library for demonstration purposes."
authors = [{ name = "Mark Richardson", email = "mrichardson82@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
keywords = ["dummypy", "analytics", "demo", "example"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "numpy>=2.2",
    "attrs>=25.3",
    "pandas>=2.2", 
]

# dependency only needed by the notebooks
[project.optional-dependencies]
notebook = [
    "loman>=0.5.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dummypy"]

# that's too brutal :-)
#[tool.deptry]
# see https://deptry.com/usage/#pep-621-dev-dependency-groups
#ignore = ["DEP002"]

[tool.deptry]
# see https://deptry.com/usage/#pep-621-dev-dependency-groups
pep621_dev_dependency_groups = ["notebook"]


[tool.deptry.package_module_name_map]
matplotlib = "matplotlib"
marimo = "marimo"
pytest = "pytest"
pandas = "pandas"
loman = "loman"
attrs = "attrs"
numpy = "numpy"
